In [1]:
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
torch.__version__

'2.0.1'

In [3]:
scaler = torch.tensor(2)

In [4]:
scaler

tensor(2)

In [5]:
scaler.ndim

0

In [7]:
#Get tensor back as python
scaler.item()

2

In [8]:
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [14]:
vector.ndim #no.of pairs of closing square brackets

1

In [15]:
vector.shape #2*1 elements

torch.Size([2])

In [16]:
matrix = torch.tensor([[1,2,],[3,4]])

In [22]:
matrix.ndim

2

In [21]:
matrix[1]

tensor([3, 4])

In [23]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [24]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
tensor.ndim

3

In [26]:
tensor.shape

torch.Size([1, 3, 3])

In [34]:
tensor[0][0][1]

tensor(2)

### random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [46]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [47]:
random_tensor.ndim

2

In [48]:
#create a tensor with similar shape to an image tensor

In [53]:
random_image = torch.rand((5,10,10,1))

In [55]:
random_image.ndim

4

In [56]:
#tensor of zeroes
zeros = torch.zeros(size=(3,4))

In [57]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
ones = torch.ones(size=(3,4))

In [59]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
#use torch.range
one_to_ten = torch.arange(0,10,step=1)

In [75]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)

In [76]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                              requires_grad=False, #computing gradients or not
                              #device="cuda"#what device the tensor is on
                              )

In [6]:
float_32_tensor.dtype

torch.float16

### tensor datatypes are one of 3 big errors that you'll run into with pytorch and deep learning:
(tensor attributes)
1) tensors not right datatype - to get data type, use tensor.dtype
2) tensors not right shape - use tensor.shape
3) tensors not on right device - can use tensor.device

In [8]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [12]:
float_16_tensor.dtype

torch.float16

### Matrix multiplication

1) Element wise
2) Matrix multiplication



In [4]:
tensor = torch.tensor([1,2,3])

In [6]:
tensor

tensor([1, 2, 3])

In [7]:
tensor * tensor

tensor([1, 4, 9])

In [9]:
torch.matmul(tensor,tensor).item()

14

### Finding min, max, mean and sum of tensors

1) Torch.mean requires a tensor of type float32

In [21]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
torch.min(x)

tensor(0)

In [23]:
torch.max(x)

tensor(90)

In [24]:
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()

tensor(45.)

In [25]:
x.dtype

torch.int64

### Finding positional min and max

In [26]:
x.argmin()

tensor(0)

In [27]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing
1) View gives a view of a tensor from the same memory as the original tensor
2) Torch.stack concatenates a series of tensors along a particular dimension (hstack) or (vstack)
3) Squeeze - removes all 1 dimensions
4) Add a 1 dimension to target tensor
5) Return a view of input with dimensions permuted (swapped)n in a certain way

In [42]:
x = torch.arange(1.,11.,1.)
x
# x.shape

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
x_reshaped = x.reshape(5,2)

In [44]:
x_reshaped.shape

torch.Size([5, 2])

In [45]:
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [47]:
z = x.view(1,10)

In [48]:
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [67]:
x_stacked = torch.stack([x,x,x,x],dim=1)

In [68]:
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [69]:
x.dim()

1

In [70]:
x_hstacked = torch.vstack([x,x,x,x])

In [66]:
x_hstacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [71]:
x.shape

torch.Size([10])

### Squeeze and unsqueeze

In [80]:
z = torch.zeros(2,1)
z

tensor([[0.],
        [0.]])

In [81]:
z.squeeze()

tensor([0., 0.])

In [87]:
z.unsqueeze(2)

tensor([[[0.]],

        [[0.]]])

In [89]:
z.dim()

2

In [91]:
z.permute(1,0)

tensor([[0., 0.]])

### Indexing in tensors

In [94]:
t = torch.arange(1,10).reshape(1,3,3)

In [100]:
t.size()
print(t)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [106]:
t[0][0][2]

tensor(3)

In [108]:
t[:,:,1]

tensor([[2, 5, 8]])

In [112]:
t[:,:,1]

tensor([[2, 5, 8]])

In [113]:
t[0,0,:]

tensor([1, 2, 3])

### Pytorch -> numpy

Numpy is a popular scientific computing library
Can convert numpy arrays to torch tensors for use in deep learning models

In [114]:
import numpy as np

In [115]:
n = np.arange(1,10)

In [119]:
t = torch.from_numpy(n)

In [120]:
t

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
n = n+1

In [123]:
n

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
t

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr = t.numpy()

In [126]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Torch reproducibility
Taking the random out of random
Essentially how neural networks learn
Use random seed to reduce randomness of tensors

In [3]:
r_tensor_a = torch.rand(3,4)
r_tensor_b = torch.rand(3,4)

In [4]:
print(r_tensor_a==r_tensor_b)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
# Random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [10]:
r_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
r_tensor_d = torch.rand(3,4)

In [11]:
print(r_tensor_c == r_tensor_d)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Use manual seed for each time you initialize a random tensor

### running tensors or pytorch objects on GPUs

In [12]:
### 1. Getting a GPU
### 2. Use google colab (free gpu)
### 3. Use Google Colab Pro


In [13]:
## check gpu access with pytorch

In [14]:
torch.cuda.is_available()

False

In [15]:
torch.has_mps

True

### MPS in MACBOOK PRO, CUDA in windows

In [16]:
device = "cuda" if torch.cuda.is_available() else "mps" if torch.mps else "cpu"

In [17]:
device

'mps'

### Putting tensors and models on GPUs

In [18]:
tensor = torch.tensor([1,2,3],device=device)

In [19]:
tensor

tensor([1, 2, 3], device='mps:0')

In [26]:
tensor_on_gpu = tensor.cpu()

In [27]:
tensor_on_gpu.device

device(type='cpu')

In [25]:
## Moving tensors back to cpus to convert to numpy array

### Exercises

In [28]:
# Random tensor with size 7*7
t = torch.rand(7,7)

In [32]:
t.size()
t.dim()

2

In [33]:
t_2 = torch.rand(1,7)

In [35]:
t.matmul(t_2.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [36]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
t = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
t_2 = torch.rand(1,7)

In [37]:
t.matmul(t_2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [39]:
torch.mps.manual_seed(1234)

In [41]:
t_gpu = torch.rand(2,3).to(device)
s_gpu = torch.rand(2,3).to(device)

In [42]:
t_gpu

tensor([[0.2823, 0.6816, 0.9152],
        [0.3971, 0.8742, 0.4194]], device='mps:0')

In [46]:
prod = t_gpu.matmul(s_gpu.T)

In [48]:
prod.max()

tensor(1.0676, device='mps:0')

In [49]:
prod.min()

tensor(0.5279, device='mps:0')

In [52]:
print(prod.argmin())
print(prod.argmax())

tensor(-9223372036854775808, device='mps:0')
tensor(-9223372036854775808, device='mps:0')


In [53]:
torch.manual_seed(7)
t1 = torch.rand(1,1,1,10)

In [55]:
t2 = torch.squeeze(t1)

In [56]:
t2.shape

torch.Size([10])

In [57]:
print(t1)
print(t1.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


In [58]:
print(t2)
print(t2.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
